// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: composable/ratelimit/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAllRateLimitsRequest struct {
}

func (m *QueryAllRateLimitsRequest) Reset()         { *m = QueryAllRateLimitsRequest{} }
func (m *QueryAllRateLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRateLimitsRequest) ProtoMessage()    {}
func (*QueryAllRateLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{0}
}
func (m *QueryAllRateLimitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRateLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRateLimitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRateLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRateLimitsRequest.Merge(m, src)
}
func (m *QueryAllRateLimitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRateLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRateLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRateLimitsRequest proto.InternalMessageInfo

type QueryAllRateLimitsResponse struct {
	RateLimits []RateLimit `protobuf:"bytes,1,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits"`
}

func (m *QueryAllRateLimitsResponse) Reset()         { *m = QueryAllRateLimitsResponse{} }
func (m *QueryAllRateLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRateLimitsResponse) ProtoMessage()    {}
func (*QueryAllRateLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{1}
}
func (m *QueryAllRateLimitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRateLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRateLimitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRateLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRateLimitsResponse.Merge(m, src)
}
func (m *QueryAllRateLimitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRateLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRateLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRateLimitsResponse proto.InternalMessageInfo

func (m *QueryAllRateLimitsResponse) GetRateLimits() []RateLimit {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

type QueryRateLimitRequest struct {
	Denom     string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *QueryRateLimitRequest) Reset()         { *m = QueryRateLimitRequest{} }
func (m *QueryRateLimitRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitRequest) ProtoMessage()    {}
func (*QueryRateLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{2}
}
func (m *QueryRateLimitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitRequest.Merge(m, src)
}
func (m *QueryRateLimitRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitRequest proto.InternalMessageInfo

func (m *QueryRateLimitRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryRateLimitRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type QueryRateLimitResponse struct {
	RateLimit *RateLimit `protobuf:"bytes,1,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
}

func (m *QueryRateLimitResponse) Reset()         { *m = QueryRateLimitResponse{} }
func (m *QueryRateLimitResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitResponse) ProtoMessage()    {}
func (*QueryRateLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{3}
}
func (m *QueryRateLimitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitResponse.Merge(m, src)
}
func (m *QueryRateLimitResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitResponse proto.InternalMessageInfo

func (m *QueryRateLimitResponse) GetRateLimit() *RateLimit {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

type QueryRateLimitsByChainIDRequest struct {
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *QueryRateLimitsByChainIDRequest) Reset()         { *m = QueryRateLimitsByChainIDRequest{} }
func (m *QueryRateLimitsByChainIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsByChainIDRequest) ProtoMessage()    {}
func (*QueryRateLimitsByChainIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{4}
}
func (m *QueryRateLimitsByChainIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsByChainIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsByChainIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsByChainIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsByChainIDRequest.Merge(m, src)
}
func (m *QueryRateLimitsByChainIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsByChainIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsByChainIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsByChainIDRequest proto.InternalMessageInfo

func (m *QueryRateLimitsByChainIDRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type QueryRateLimitsByChainIDResponse struct {
	RateLimits []RateLimit `protobuf:"bytes,1,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits"`
}

func (m *QueryRateLimitsByChainIDResponse) Reset()         { *m = QueryRateLimitsByChainIDResponse{} }
func (m *QueryRateLimitsByChainIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsByChainIDResponse) ProtoMessage()    {}
func (*QueryRateLimitsByChainIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{5}
}
func (m *QueryRateLimitsByChainIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsByChainIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsByChainIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsByChainIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsByChainIDResponse.Merge(m, src)
}
func (m *QueryRateLimitsByChainIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsByChainIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsByChainIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsByChainIDResponse proto.InternalMessageInfo

func (m *QueryRateLimitsByChainIDResponse) GetRateLimits() []RateLimit {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

type QueryRateLimitsByChannelIDRequest struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *QueryRateLimitsByChannelIDRequest) Reset()         { *m = QueryRateLimitsByChannelIDRequest{} }
func (m *QueryRateLimitsByChannelIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsByChannelIDRequest) ProtoMessage()    {}
func (*QueryRateLimitsByChannelIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{6}
}
func (m *QueryRateLimitsByChannelIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsByChannelIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsByChannelIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsByChannelIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsByChannelIDRequest.Merge(m, src)
}
func (m *QueryRateLimitsByChannelIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsByChannelIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsByChannelIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsByChannelIDRequest proto.InternalMessageInfo

func (m *QueryRateLimitsByChannelIDRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type QueryRateLimitsByChannelIDResponse struct {
	RateLimits []RateLimit `protobuf:"bytes,1,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits"`
}

func (m *QueryRateLimitsByChannelIDResponse) Reset()         { *m = QueryRateLimitsByChannelIDResponse{} }
func (m *QueryRateLimitsByChannelIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsByChannelIDResponse) ProtoMessage()    {}
func (*QueryRateLimitsByChannelIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{7}
}
func (m *QueryRateLimitsByChannelIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsByChannelIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsByChannelIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsByChannelIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsByChannelIDResponse.Merge(m, src)
}
func (m *QueryRateLimitsByChannelIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsByChannelIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsByChannelIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsByChannelIDResponse proto.InternalMessageInfo

func (m *QueryRateLimitsByChannelIDResponse) GetRateLimits() []RateLimit {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

type QueryAllWhitelistedAddressesRequest struct {
}

func (m *QueryAllWhitelistedAddressesRequest) Reset()         { *m = QueryAllWhitelistedAddressesRequest{} }
func (m *QueryAllWhitelistedAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllWhitelistedAddressesRequest) ProtoMessage()    {}
func (*QueryAllWhitelistedAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{8}
}
func (m *QueryAllWhitelistedAddressesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllWhitelistedAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllWhitelistedAddressesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllWhitelistedAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllWhitelistedAddressesRequest.Merge(m, src)
}
func (m *QueryAllWhitelistedAddressesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllWhitelistedAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllWhitelistedAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllWhitelistedAddressesRequest proto.InternalMessageInfo

type QueryAllWhitelistedAddressesResponse struct {
	AddressPairs []WhitelistedAddressPair `protobuf:"bytes,1,rep,name=address_pairs,json=addressPairs,proto3" json:"address_pairs"`
}

func (m *QueryAllWhitelistedAddressesResponse) Reset()         { *m = QueryAllWhitelistedAddressesResponse{} }
func (m *QueryAllWhitelistedAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllWhitelistedAddressesResponse) ProtoMessage()    {}
func (*QueryAllWhitelistedAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd0dc17fb77b132, []int{9}
}
func (m *QueryAllWhitelistedAddressesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllWhitelistedAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllWhitelistedAddressesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllWhitelistedAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllWhitelistedAddressesResponse.Merge(m, src)
}
func (m *QueryAllWhitelistedAddressesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllWhitelistedAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllWhitelistedAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllWhitelistedAddressesResponse proto.InternalMessageInfo

func (m *QueryAllWhitelistedAddressesResponse) GetAddressPairs() []WhitelistedAddressPair {
	if m != nil {
		return m.AddressPairs
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryAllRateLimitsRequest)(nil), "composable.ratelimit.v1beta1.QueryAllRateLimitsRequest")
	proto.RegisterType((*QueryAllRateLimitsResponse)(nil), "composable.ratelimit.v1beta1.QueryAllRateLimitsResponse")
	proto.RegisterType((*QueryRateLimitRequest)(nil), "composable.ratelimit.v1beta1.QueryRateLimitRequest")
	proto.RegisterType((*QueryRateLimitResponse)(nil), "composable.ratelimit.v1beta1.QueryRateLimitResponse")
	proto.RegisterType((*QueryRateLimitsByChainIDRequest)(nil), "composable.ratelimit.v1beta1.QueryRateLimitsByChainIDRequest")
	proto.RegisterType((*QueryRateLimitsByChainIDResponse)(nil), "composable.ratelimit.v1beta1.QueryRateLimitsByChainIDResponse")
	proto.RegisterType((*QueryRateLimitsByChannelIDRequest)(nil), "composable.ratelimit.v1beta1.QueryRateLimitsByChannelIDRequest")
	proto.RegisterType((*QueryRateLimitsByChannelIDResponse)(nil), "composable.ratelimit.v1beta1.QueryRateLimitsByChannelIDResponse")
	proto.RegisterType((*QueryAllWhitelistedAddressesRequest)(nil), "composable.ratelimit.v1beta1.QueryAllWhitelistedAddressesRequest")
	proto.RegisterType((*QueryAllWhitelistedAddressesResponse)(nil), "composable.ratelimit.v1beta1.QueryAllWhitelistedAddressesResponse")
}

func init() {
	proto.RegisterFile("composable/ratelimit/v1beta1/query.proto", fileDescriptor_dcd0dc17fb77b132)
}

var fileDescriptor_dcd0dc17fb77b132 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xb3, 0xfd, 0xbe, 0x52, 0x32, 0xa5, 0x07, 0x96, 0x16, 0x52, 0x53, 0xdc, 0x60, 0x40,
	0x44, 0x2a, 0x8d, 0xd5, 0xa6, 0x55, 0x39, 0x50, 0x20, 0x01, 0x21, 0x45, 0xaa, 0x10, 0xe4, 0x82,
	0xc4, 0xc5, 0x6c, 0xe2, 0x55, 0x62, 0xc9, 0xf1, 0xba, 0xde, 0x2d, 0x10, 0xa1, 0x5e, 0xb8, 0x70,
	0x45, 0xe2, 0x35, 0xb8, 0xf2, 0x0e, 0xe5, 0x56, 0x84, 0x90, 0x38, 0x21, 0x94, 0x20, 0x9e, 0x03,
	0x79, 0xed, 0xd8, 0x24, 0x4d, 0x5c, 0xa7, 0xa8, 0xb7, 0xf5, 0xec, 0xcc, 0x7f, 0x7e, 0x33, 0xbb,
	0xb3, 0x86, 0x42, 0x83, 0xb5, 0x5d, 0xc6, 0x49, 0xdd, 0xa6, 0xba, 0x47, 0x04, 0xb5, 0xad, 0xb6,
	0x25, 0xf4, 0x97, 0x6b, 0x75, 0x2a, 0xc8, 0x9a, 0xbe, 0xbb, 0x47, 0xbd, 0x4e, 0xd1, 0xf5, 0x98,
	0x60, 0x78, 0x29, 0xf6, 0x2c, 0x46, 0x9e, 0xc5, 0xd0, 0x53, 0xb9, 0x95, 0xa8, 0x13, 0xfb, 0x4b,
	0x2d, 0x65, 0xa9, 0xc9, 0x58, 0xd3, 0xa6, 0x3a, 0x71, 0x2d, 0x9d, 0x38, 0x0e, 0x13, 0x44, 0x58,
	0xcc, 0xe1, 0xe1, 0xee, 0x7c, 0x93, 0x35, 0x99, 0x5c, 0xea, 0xfe, 0x2a, 0xb0, 0x6a, 0x97, 0x61,
	0xf1, 0xa9, 0x8f, 0x53, 0xb6, 0xed, 0x1a, 0x11, 0x74, 0xc7, 0x97, 0xe3, 0x35, 0xba, 0xbb, 0x47,
	0xb9, 0xd0, 0x6c, 0x50, 0x46, 0x6d, 0x72, 0x97, 0x39, 0x9c, 0xe2, 0xc7, 0x30, 0xeb, 0x13, 0x18,
	0x12, 0x81, 0xe7, 0x50, 0xfe, 0xbf, 0xc2, 0xec, 0xfa, 0xcd, 0x62, 0x52, 0x41, 0xc5, 0x48, 0xa6,
	0xf2, 0xff, 0xc1, 0x8f, 0xe5, 0x4c, 0x0d, 0xbc, 0x48, 0x57, 0xdb, 0x81, 0x05, 0x99, 0x2d, 0xf2,
	0x09, 0x31, 0xf0, 0x3c, 0x4c, 0x9b, 0xd4, 0x61, 0xed, 0x1c, 0xca, 0xa3, 0x42, 0xb6, 0x16, 0x7c,
	0xe0, 0x2b, 0x00, 0x8d, 0x16, 0x71, 0x1c, 0x6a, 0x1b, 0x96, 0x99, 0x9b, 0x92, 0x5b, 0xd9, 0xd0,
	0x52, 0x35, 0xb5, 0x17, 0x70, 0x71, 0x58, 0x2d, 0xe4, 0x7e, 0x04, 0x10, 0x73, 0x4b, 0xcd, 0xf4,
	0xd8, 0xb5, 0x6c, 0x04, 0xac, 0xdd, 0x81, 0xe5, 0xc1, 0x0c, 0xbc, 0xd2, 0x79, 0xd0, 0x22, 0x96,
	0x53, 0x7d, 0xd8, 0x27, 0x5f, 0x84, 0xb3, 0x0d, 0xdf, 0xe2, 0x13, 0x06, 0xf0, 0x33, 0xf2, 0xbb,
	0x6a, 0x6a, 0x1e, 0xe4, 0xc7, 0x47, 0x9f, 0x52, 0x87, 0x2b, 0x70, 0x75, 0x54, 0x4e, 0xd9, 0xb1,
	0x88, 0x79, 0xb0, 0xaf, 0x68, 0xb8, 0xaf, 0x02, 0xb4, 0x24, 0x8d, 0x53, 0x22, 0xbf, 0x01, 0xd7,
	0xfa, 0x37, 0xf1, 0x59, 0xcb, 0xf2, 0x23, 0xb9, 0xa0, 0x66, 0xd9, 0x34, 0x3d, 0xca, 0x39, 0x8d,
	0x2e, 0xec, 0x3b, 0x04, 0xd7, 0x93, 0xfd, 0x42, 0x3e, 0x03, 0xe6, 0x48, 0x60, 0x34, 0x5c, 0x62,
	0x79, 0x7d, 0xc2, 0x8d, 0x64, 0xc2, 0xa3, 0x92, 0x4f, 0x88, 0xe5, 0x85, 0xb8, 0xe7, 0x48, 0x6c,
	0xe2, 0xeb, 0xbf, 0x67, 0x60, 0x5a, 0x92, 0xe0, 0x8f, 0x08, 0xe6, 0x06, 0x06, 0x08, 0x6f, 0x25,
	0x67, 0x19, 0x3b, 0x8f, 0xca, 0xed, 0xc9, 0x03, 0x83, 0x7a, 0xb5, 0xc2, 0xdb, 0xaf, 0xbf, 0x3e,
	0x4c, 0x69, 0x38, 0xaf, 0x8f, 0x7c, 0x51, 0xa2, 0x15, 0xc7, 0x9f, 0x10, 0x64, 0x23, 0x01, 0x5c,
	0x4a, 0x91, 0x71, 0x78, 0x5e, 0x95, 0x8d, 0xc9, 0x82, 0x42, 0xc4, 0x6d, 0x89, 0xb8, 0x85, 0x37,
	0x8f, 0x41, 0xd4, 0xdf, 0xc4, 0xd7, 0x73, 0x5f, 0xaf, 0x77, 0x8c, 0xe0, 0x39, 0xf8, 0x8c, 0xe0,
	0xc2, 0x88, 0x59, 0xc2, 0xdb, 0x93, 0xc0, 0x1c, 0x99, 0x60, 0xe5, 0xee, 0x49, 0xc3, 0xc3, 0xaa,
	0x4a, 0xb2, 0xaa, 0x55, 0xbc, 0x72, 0x5c, 0xe3, 0x65, 0x59, 0xf2, 0xa5, 0xd8, 0xc7, 0x5f, 0x10,
	0x2c, 0x8c, 0x9c, 0x2f, 0x7c, 0x6f, 0x72, 0x9c, 0x81, 0xe9, 0x56, 0xee, 0x9f, 0x5c, 0x20, 0xac,
	0x68, 0x53, 0x56, 0xa4, 0xe3, 0xd5, 0x54, 0x15, 0xf5, 0x0f, 0x0a, 0x7f, 0x43, 0x70, 0x69, 0xcc,
	0x54, 0xe2, 0x72, 0xba, 0x7b, 0x9d, 0x30, 0xf9, 0x4a, 0xe5, 0x5f, 0x24, 0xd2, 0x9d, 0xd5, 0xab,
	0x38, 0xd6, 0x20, 0xfd, 0xe0, 0xca, 0xca, 0x41, 0x57, 0x45, 0x87, 0x5d, 0x15, 0xfd, 0xec, 0xaa,
	0xe8, 0x7d, 0x4f, 0xcd, 0x1c, 0xf6, 0xd4, 0xcc, 0xf7, 0x9e, 0x9a, 0x79, 0x7e, 0xfe, 0xf5, 0x5f,
	0xc1, 0xa2, 0xe3, 0x52, 0x5e, 0x3f, 0x23, 0x7f, 0xba, 0xa5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x17, 0xb4, 0x11, 0x82, 0x20, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	AllRateLimits(ctx context.Context, in *QueryAllRateLimitsRequest, opts ...grpc.CallOption) (*QueryAllRateLimitsResponse, error)
	RateLimit(ctx context.Context, in *QueryRateLimitRequest, opts ...grpc.CallOption) (*QueryRateLimitResponse, error)
	RateLimitsByChainID(ctx context.Context, in *QueryRateLimitsByChainIDRequest, opts ...grpc.CallOption) (*QueryRateLimitsByChainIDResponse, error)
	RateLimitsByChannelID(ctx context.Context, in *QueryRateLimitsByChannelIDRequest, opts ...grpc.CallOption) (*QueryRateLimitsByChannelIDResponse, error)
	AllWhitelistedAddresses(ctx context.Context, in *QueryAllWhitelistedAddressesRequest, opts ...grpc.CallOption) (*QueryAllWhitelistedAddressesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) AllRateLimits(ctx context.Context, in *QueryAllRateLimitsRequest, opts ...grpc.CallOption) (*QueryAllRateLimitsResponse, error) {
	out := new(QueryAllRateLimitsResponse)
	err := c.cc.Invoke(ctx, "/composable.ratelimit.v1beta1.Query/AllRateLimits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RateLimit(ctx context.Context, in *QueryRateLimitRequest, opts ...grpc.CallOption) (*QueryRateLimitResponse, error) {
	out := new(QueryRateLimitResponse)
	err := c.cc.Invoke(ctx, "/composable.ratelimit.v1beta1.Query/RateLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RateLimitsByChainID(ctx context.Context, in *QueryRateLimitsByChainIDRequest, opts ...grpc.CallOption) (*QueryRateLimitsByChainIDResponse, error) {
	out := new(QueryRateLimitsByChainIDResponse)
	err := c.cc.Invoke(ctx, "/composable.ratelimit.v1beta1.Query/RateLimitsByChainID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RateLimitsByChannelID(ctx context.Context, in *QueryRateLimitsByChannelIDRequest, opts ...grpc.CallOption) (*QueryRateLimitsByChannelIDResponse, error) {
	out := new(QueryRateLimitsByChannelIDResponse)
	err := c.cc.Invoke(ctx, "/composable.ratelimit.v1beta1.Query/RateLimitsByChannelID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllWhitelistedAddresses(ctx context.Context, in *QueryAllWhitelistedAddressesRequest, opts ...grpc.CallOption) (*QueryAllWhitelistedAddressesResponse, error) {
	out := new(QueryAllWhitelistedAddressesResponse)
	err := c.cc.Invoke(ctx, "/composable.ratelimit.v1beta1.Query/AllWhitelistedAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	AllRateLimits(context.Context, *QueryAllRateLimitsRequest) (*QueryAllRateLimitsResponse, error)
	RateLimit(context.Context, *QueryRateLimitRequest) (*QueryRateLimitResponse, error)
	RateLimitsByChainID(context.Context, *QueryRateLimitsByChainIDRequest) (*QueryRateLimitsByChainIDResponse, error)
	RateLimitsByChannelID(context.Context, *QueryRateLimitsByChannelIDRequest) (*QueryRateLimitsByChannelIDResponse, error)
	AllWhitelistedAddresses(context.Context, *QueryAllWhitelistedAddressesRequest) (*QueryAllWhitelistedAddressesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) AllRateLimits(ctx context.Context, req *QueryAllRateLimitsRequest) (*QueryAllRateLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllRateLimits not implemented")
}
func (*UnimplementedQueryServer) RateLimit(ctx context.Context, req *QueryRateLimitRequest) (*QueryRateLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateLimit not implemented")
}
func (*UnimplementedQueryServer) RateLimitsByChainID(ctx context.Context, req *QueryRateLimitsByChainIDRequest) (*QueryRateLimitsByChainIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateLimitsByChainID not implemented")
}
func (*UnimplementedQueryServer) RateLimitsByChannelID(ctx context.Context, req *QueryRateLimitsByChannelIDRequest) (*QueryRateLimitsByChannelIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateLimitsByChannelID not implemented")
}
func (*UnimplementedQueryServer) AllWhitelistedAddresses(ctx context.Context, req *QueryAllWhitelistedAddressesRequest) (*QueryAllWhitelistedAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllWhitelistedAddresses not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_AllRateLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRateLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllRateLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.ratelimit.v1beta1.Query/AllRateLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllRateLimits(ctx, req.(*QueryAllRateLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.ratelimit.v1beta1.Query/RateLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RateLimit(ctx, req.(*QueryRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RateLimitsByChainID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitsByChainIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RateLimitsByChainID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.ratelimit.v1beta1.Query/RateLimitsByChainID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RateLimitsByChainID(ctx, req.(*QueryRateLimitsByChainIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RateLimitsByChannelID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitsByChannelIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RateLimitsByChannelID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.ratelimit.v1beta1.Query/RateLimitsByChannelID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RateLimitsByChannelID(ctx, req.(*QueryRateLimitsByChannelIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllWhitelistedAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllWhitelistedAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllWhitelistedAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.ratelimit.v1beta1.Query/AllWhitelistedAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllWhitelistedAddresses(ctx, req.(*QueryAllWhitelistedAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "composable.ratelimit.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllRateLimits",
			Handler:    _Query_AllRateLimits_Handler,
		},
		{
			MethodName: "RateLimit",
			Handler:    _Query_RateLimit_Handler,
		},
		{
			MethodName: "RateLimitsByChainID",
			Handler:    _Query_RateLimitsByChainID_Handler,
		},
		{
			MethodName: "RateLimitsByChannelID",
			Handler:    _Query_RateLimitsByChannelID_Handler,
		},
		{
			MethodName: "AllWhitelistedAddresses",
			Handler:    _Query_AllWhitelistedAddresses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "composable/ratelimit/v1beta1/query.proto",
}

func (m *QueryAllRateLimitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRateLimitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRateLimitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllRateLimitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRateLimitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRateLimitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for iNdEx := len(m.RateLimits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RateLimits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RateLimit != nil {
		{
			size, err := m.RateLimit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitsByChainIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsByChainIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsByChainIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitsByChainIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsByChainIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsByChainIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for iNdEx := len(m.RateLimits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RateLimits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitsByChannelIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsByChannelIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsByChannelIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitsByChannelIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsByChannelIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsByChannelIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for iNdEx := len(m.RateLimits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RateLimits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllWhitelistedAddressesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllWhitelistedAddressesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllWhitelistedAddressesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllWhitelistedAddressesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllWhitelistedAddressesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllWhitelistedAddressesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AddressPairs) > 0 {
		for iNdEx := len(m.AddressPairs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AddressPairs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAllRateLimitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllRateLimitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for _, e := range m.RateLimits {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryRateLimitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRateLimitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RateLimit != nil {
		l = m.RateLimit.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRateLimitsByChainIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRateLimitsByChainIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for _, e := range m.RateLimits {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryRateLimitsByChannelIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRateLimitsByChannelIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for _, e := range m.RateLimits {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAllWhitelistedAddressesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllWhitelistedAddressesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AddressPairs) > 0 {
		for _, e := range m.AddressPairs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAllRateLimitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRateLimitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRateLimitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRateLimitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRateLimitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRateLimitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RateLimits = append(m.RateLimits, RateLimit{})
			if err := m.RateLimits[len(m.RateLimits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RateLimit == nil {
				m.RateLimit = &RateLimit{}
			}
			if err := m.RateLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitsByChainIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsByChainIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsByChainIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitsByChainIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsByChainIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsByChainIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RateLimits = append(m.RateLimits, RateLimit{})
			if err := m.RateLimits[len(m.RateLimits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitsByChannelIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitsByChannelIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RateLimits = append(m.RateLimits, RateLimit{})
			if err := m.RateLimits[len(m.RateLimits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllWhitelistedAddressesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllWhitelistedAddressesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllWhitelistedAddressesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllWhitelistedAddressesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllWhitelistedAddressesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllWhitelistedAddressesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressPairs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressPairs = append(m.AddressPairs, WhitelistedAddressPair{})
			if err := m.AddressPairs[len(m.AddressPairs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
