// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: centauri/mint/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgFundModuleAccount struct {
	FromAddress string                                   `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount" yaml:"amount"`
}

func (m *MsgFundModuleAccount) Reset()         { *m = MsgFundModuleAccount{} }
func (m *MsgFundModuleAccount) String() string { return proto.CompactTextString(m) }
func (*MsgFundModuleAccount) ProtoMessage()    {}
func (*MsgFundModuleAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_80c8af29bb20a4d0, []int{0}
}
func (m *MsgFundModuleAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundModuleAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundModuleAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundModuleAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundModuleAccount.Merge(m, src)
}
func (m *MsgFundModuleAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundModuleAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundModuleAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundModuleAccount proto.InternalMessageInfo

func (m *MsgFundModuleAccount) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgFundModuleAccount) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgFundModuleAccountResponse struct {
}

func (m *MsgFundModuleAccountResponse) Reset()         { *m = MsgFundModuleAccountResponse{} }
func (m *MsgFundModuleAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFundModuleAccountResponse) ProtoMessage()    {}
func (*MsgFundModuleAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80c8af29bb20a4d0, []int{1}
}
func (m *MsgFundModuleAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundModuleAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundModuleAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundModuleAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundModuleAccountResponse.Merge(m, src)
}
func (m *MsgFundModuleAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundModuleAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundModuleAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundModuleAccountResponse proto.InternalMessageInfo

// MsgAddAccountToFundModuleSet add account in to allowed fund module set
type MsgAddAccountToFundModuleSet struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority      string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty" yaml:"authority"`
	AllowedAddress string `protobuf:"bytes,2,opt,name=allowed_address,json=allowedAddress,proto3" json:"allowed_address,omitempty" yaml:"allowed_address"`
}

func (m *MsgAddAccountToFundModuleSet) Reset()         { *m = MsgAddAccountToFundModuleSet{} }
func (m *MsgAddAccountToFundModuleSet) String() string { return proto.CompactTextString(m) }
func (*MsgAddAccountToFundModuleSet) ProtoMessage()    {}
func (*MsgAddAccountToFundModuleSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_80c8af29bb20a4d0, []int{2}
}
func (m *MsgAddAccountToFundModuleSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddAccountToFundModuleSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddAccountToFundModuleSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddAccountToFundModuleSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddAccountToFundModuleSet.Merge(m, src)
}
func (m *MsgAddAccountToFundModuleSet) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddAccountToFundModuleSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddAccountToFundModuleSet.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddAccountToFundModuleSet proto.InternalMessageInfo

func (m *MsgAddAccountToFundModuleSet) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgAddAccountToFundModuleSet) GetAllowedAddress() string {
	if m != nil {
		return m.AllowedAddress
	}
	return ""
}

type MsgAddAccountToFundModuleSetResponse struct {
}

func (m *MsgAddAccountToFundModuleSetResponse) Reset()         { *m = MsgAddAccountToFundModuleSetResponse{} }
func (m *MsgAddAccountToFundModuleSetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddAccountToFundModuleSetResponse) ProtoMessage()    {}
func (*MsgAddAccountToFundModuleSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80c8af29bb20a4d0, []int{3}
}
func (m *MsgAddAccountToFundModuleSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddAccountToFundModuleSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddAccountToFundModuleSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddAccountToFundModuleSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddAccountToFundModuleSetResponse.Merge(m, src)
}
func (m *MsgAddAccountToFundModuleSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddAccountToFundModuleSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddAccountToFundModuleSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddAccountToFundModuleSetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgFundModuleAccount)(nil), "centauri.mint.v1beta1.MsgFundModuleAccount")
	proto.RegisterType((*MsgFundModuleAccountResponse)(nil), "centauri.mint.v1beta1.MsgFundModuleAccountResponse")
	proto.RegisterType((*MsgAddAccountToFundModuleSet)(nil), "centauri.mint.v1beta1.MsgAddAccountToFundModuleSet")
	proto.RegisterType((*MsgAddAccountToFundModuleSetResponse)(nil), "centauri.mint.v1beta1.MsgAddAccountToFundModuleSetResponse")
}

func init() { proto.RegisterFile("centauri/mint/v1beta1/tx.proto", fileDescriptor_80c8af29bb20a4d0) }

var fileDescriptor_80c8af29bb20a4d0 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcb, 0x6e, 0xd4, 0x30,
	0x14, 0x8d, 0xa7, 0x52, 0xa5, 0xba, 0xe5, 0x15, 0x0d, 0xa8, 0x8d, 0x90, 0x53, 0x2c, 0x54, 0x8d,
	0x84, 0x70, 0xd4, 0xe9, 0x0e, 0x56, 0x99, 0x4a, 0xec, 0x66, 0x13, 0x58, 0xb1, 0x41, 0x4e, 0x6c,
	0xd2, 0x88, 0x24, 0x77, 0x14, 0x3b, 0xd0, 0xf9, 0x07, 0x90, 0xd8, 0xf1, 0x0f, 0x6c, 0xf8, 0x8d,
	0x2e, 0xbb, 0x64, 0x15, 0xd0, 0xcc, 0x1f, 0xcc, 0x17, 0xa0, 0xc4, 0x4e, 0x2b, 0xc4, 0x74, 0x24,
	0xba, 0x4a, 0x74, 0xcf, 0x39, 0xf7, 0x1e, 0x1f, 0x5f, 0x63, 0x92, 0xc8, 0x52, 0xf3, 0xba, 0xca,
	0x82, 0x22, 0x2b, 0x75, 0xf0, 0xf1, 0x38, 0x96, 0x9a, 0x1f, 0x07, 0xfa, 0x9c, 0xcd, 0x2a, 0xd0,
	0xe0, 0x3e, 0xec, 0x71, 0xd6, 0xe2, 0xcc, 0xe2, 0xde, 0x30, 0x85, 0x14, 0x3a, 0x46, 0xd0, 0xfe,
	0x19, 0xb2, 0x47, 0x12, 0x50, 0x05, 0xa8, 0x20, 0xe6, 0x4a, 0x5e, 0xb5, 0x4a, 0x20, 0x2b, 0x0d,
	0x4e, 0x7f, 0x20, 0x3c, 0x9c, 0xaa, 0xf4, 0x55, 0x5d, 0x8a, 0x29, 0x88, 0x3a, 0x97, 0x61, 0x92,
	0x40, 0x5d, 0x6a, 0xf7, 0x09, 0xde, 0x7b, 0x5f, 0x41, 0xf1, 0x8e, 0x0b, 0x51, 0x49, 0xa5, 0xf6,
	0xd1, 0x21, 0x1a, 0xed, 0x44, 0xbb, 0x6d, 0x2d, 0x34, 0x25, 0x57, 0xe3, 0x6d, 0x5e, 0xb4, 0xe4,
	0xfd, 0xc1, 0xe1, 0xd6, 0x68, 0x77, 0x7c, 0xc0, 0xcc, 0x30, 0xd6, 0x0e, 0xeb, 0x7d, 0xb1, 0x53,
	0xc8, 0xca, 0x49, 0x78, 0xd1, 0xf8, 0xce, 0xaa, 0xf1, 0xef, 0xcc, 0x79, 0x91, 0xbf, 0xa0, 0x46,
	0x46, 0xbf, 0xff, 0xf2, 0x47, 0x69, 0xa6, 0xcf, 0xea, 0x98, 0x25, 0x50, 0x04, 0xd6, 0xaa, 0xf9,
	0x3c, 0x57, 0xe2, 0x43, 0xa0, 0xe7, 0x33, 0xa9, 0xba, 0x0e, 0x2a, 0xb2, 0xb3, 0x28, 0xc1, 0x8f,
	0xd7, 0x19, 0x8e, 0xa4, 0x9a, 0x41, 0xa9, 0x24, 0xfd, 0x86, 0x3a, 0x42, 0x28, 0x84, 0x45, 0xde,
	0xc0, 0x35, 0xf9, 0xb5, 0xd4, 0xee, 0x18, 0xef, 0xf0, 0x5a, 0x9f, 0x41, 0x95, 0xe9, 0xb9, 0x39,
	0xd6, 0x64, 0xb8, 0x6a, 0xfc, 0xfb, 0xd6, 0x5a, 0x0f, 0xd1, 0xe8, 0x9a, 0xe6, 0x9e, 0xe2, 0x7b,
	0x3c, 0xcf, 0xe1, 0x93, 0x14, 0x57, 0x81, 0x0c, 0x3a, 0xa5, 0xb7, 0x6a, 0xfc, 0x47, 0x56, 0xf9,
	0x37, 0x81, 0x46, 0x77, 0x6d, 0xc5, 0xe6, 0x45, 0x8f, 0xf0, 0xd3, 0x4d, 0xc6, 0xfa, 0x13, 0x8c,
	0x3f, 0x0f, 0xf0, 0xd6, 0x54, 0xa5, 0x6e, 0x8d, 0x1f, 0xfc, 0x7b, 0x2f, 0xcf, 0xd8, 0xda, 0xeb,
	0x67, 0xeb, 0x32, 0xf1, 0x4e, 0xfe, 0x83, 0xdc, 0x8f, 0x77, 0xbf, 0x20, 0x7c, 0x70, 0x73, 0x7a,
	0x1b, 0x5a, 0xde, 0x28, 0xf2, 0x5e, 0xde, 0x42, 0xd4, 0xfb, 0x99, 0x1c, 0x5d, 0x2c, 0x08, 0xba,
	0x5c, 0x10, 0xf4, 0x7b, 0x41, 0xd0, 0xd7, 0x25, 0x71, 0x2e, 0x97, 0xc4, 0xf9, 0xb9, 0x24, 0xce,
	0xdb, 0xbd, 0x73, 0xf3, 0x44, 0xba, 0x35, 0x89, 0xb7, 0xbb, 0x8d, 0x3e, 0xf9, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xc0, 0x8a, 0x38, 0x7f, 0x40, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	FundModuleAccount(ctx context.Context, in *MsgFundModuleAccount, opts ...grpc.CallOption) (*MsgFundModuleAccountResponse, error)
	AddAccountToFundModuleSet(ctx context.Context, in *MsgAddAccountToFundModuleSet, opts ...grpc.CallOption) (*MsgAddAccountToFundModuleSetResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) FundModuleAccount(ctx context.Context, in *MsgFundModuleAccount, opts ...grpc.CallOption) (*MsgFundModuleAccountResponse, error) {
	out := new(MsgFundModuleAccountResponse)
	err := c.cc.Invoke(ctx, "/centauri.mint.v1beta1.Msg/FundModuleAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddAccountToFundModuleSet(ctx context.Context, in *MsgAddAccountToFundModuleSet, opts ...grpc.CallOption) (*MsgAddAccountToFundModuleSetResponse, error) {
	out := new(MsgAddAccountToFundModuleSetResponse)
	err := c.cc.Invoke(ctx, "/centauri.mint.v1beta1.Msg/AddAccountToFundModuleSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	FundModuleAccount(context.Context, *MsgFundModuleAccount) (*MsgFundModuleAccountResponse, error)
	AddAccountToFundModuleSet(context.Context, *MsgAddAccountToFundModuleSet) (*MsgAddAccountToFundModuleSetResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) FundModuleAccount(ctx context.Context, req *MsgFundModuleAccount) (*MsgFundModuleAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundModuleAccount not implemented")
}
func (*UnimplementedMsgServer) AddAccountToFundModuleSet(ctx context.Context, req *MsgAddAccountToFundModuleSet) (*MsgAddAccountToFundModuleSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountToFundModuleSet not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_FundModuleAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFundModuleAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FundModuleAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/centauri.mint.v1beta1.Msg/FundModuleAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FundModuleAccount(ctx, req.(*MsgFundModuleAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddAccountToFundModuleSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddAccountToFundModuleSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddAccountToFundModuleSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/centauri.mint.v1beta1.Msg/AddAccountToFundModuleSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddAccountToFundModuleSet(ctx, req.(*MsgAddAccountToFundModuleSet))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "centauri.mint.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FundModuleAccount",
			Handler:    _Msg_FundModuleAccount_Handler,
		},
		{
			MethodName: "AddAccountToFundModuleSet",
			Handler:    _Msg_AddAccountToFundModuleSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "centauri/mint/v1beta1/tx.proto",
}

func (m *MsgFundModuleAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundModuleAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundModuleAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFundModuleAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundModuleAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundModuleAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddAccountToFundModuleSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddAccountToFundModuleSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddAccountToFundModuleSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedAddress) > 0 {
		i -= len(m.AllowedAddress)
		copy(dAtA[i:], m.AllowedAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AllowedAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddAccountToFundModuleSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddAccountToFundModuleSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddAccountToFundModuleSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgFundModuleAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgFundModuleAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddAccountToFundModuleSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AllowedAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddAccountToFundModuleSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgFundModuleAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundModuleAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundModuleAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFundModuleAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundModuleAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundModuleAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddAccountToFundModuleSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddAccountToFundModuleSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddAccountToFundModuleSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddAccountToFundModuleSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddAccountToFundModuleSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddAccountToFundModuleSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
