// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: composable/stakingmiddleware/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
//
// Since: cosmos-sdk 0.47
type MsgUpdateEpochParams struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the x/stakingmiddleware parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateEpochParams) Reset()         { *m = MsgUpdateEpochParams{} }
func (m *MsgUpdateEpochParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEpochParams) ProtoMessage()    {}
func (*MsgUpdateEpochParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef8bcd16d104cd6, []int{0}
}
func (m *MsgUpdateEpochParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEpochParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEpochParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEpochParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEpochParams.Merge(m, src)
}
func (m *MsgUpdateEpochParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEpochParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEpochParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEpochParams proto.InternalMessageInfo

func (m *MsgUpdateEpochParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateEpochParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParamsEpochResponse struct {
}

func (m *MsgUpdateParamsEpochResponse) Reset()         { *m = MsgUpdateParamsEpochResponse{} }
func (m *MsgUpdateParamsEpochResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsEpochResponse) ProtoMessage()    {}
func (*MsgUpdateParamsEpochResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef8bcd16d104cd6, []int{1}
}
func (m *MsgUpdateParamsEpochResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsEpochResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsEpochResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsEpochResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsEpochResponse.Merge(m, src)
}
func (m *MsgUpdateParamsEpochResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsEpochResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsEpochResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsEpochResponse proto.InternalMessageInfo

type MsgAddRevenueFundsToStakingParams struct {
	FromAddress string                                   `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgAddRevenueFundsToStakingParams) Reset()         { *m = MsgAddRevenueFundsToStakingParams{} }
func (m *MsgAddRevenueFundsToStakingParams) String() string { return proto.CompactTextString(m) }
func (*MsgAddRevenueFundsToStakingParams) ProtoMessage()    {}
func (*MsgAddRevenueFundsToStakingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef8bcd16d104cd6, []int{2}
}
func (m *MsgAddRevenueFundsToStakingParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddRevenueFundsToStakingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddRevenueFundsToStakingParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddRevenueFundsToStakingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRevenueFundsToStakingParams.Merge(m, src)
}
func (m *MsgAddRevenueFundsToStakingParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddRevenueFundsToStakingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRevenueFundsToStakingParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRevenueFundsToStakingParams proto.InternalMessageInfo

func (m *MsgAddRevenueFundsToStakingParams) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgAddRevenueFundsToStakingParams) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgAddRevenueFundsToStakingResponse struct {
}

func (m *MsgAddRevenueFundsToStakingResponse) Reset()         { *m = MsgAddRevenueFundsToStakingResponse{} }
func (m *MsgAddRevenueFundsToStakingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddRevenueFundsToStakingResponse) ProtoMessage()    {}
func (*MsgAddRevenueFundsToStakingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef8bcd16d104cd6, []int{3}
}
func (m *MsgAddRevenueFundsToStakingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddRevenueFundsToStakingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddRevenueFundsToStakingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddRevenueFundsToStakingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRevenueFundsToStakingResponse.Merge(m, src)
}
func (m *MsgAddRevenueFundsToStakingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddRevenueFundsToStakingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRevenueFundsToStakingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRevenueFundsToStakingResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateEpochParams)(nil), "composable.stakingmiddleware.v1beta1.MsgUpdateEpochParams")
	proto.RegisterType((*MsgUpdateParamsEpochResponse)(nil), "composable.stakingmiddleware.v1beta1.MsgUpdateParamsEpochResponse")
	proto.RegisterType((*MsgAddRevenueFundsToStakingParams)(nil), "composable.stakingmiddleware.v1beta1.MsgAddRevenueFundsToStakingParams")
	proto.RegisterType((*MsgAddRevenueFundsToStakingResponse)(nil), "composable.stakingmiddleware.v1beta1.MsgAddRevenueFundsToStakingResponse")
}

func init() {
	proto.RegisterFile("composable/stakingmiddleware/v1beta1/tx.proto", fileDescriptor_4ef8bcd16d104cd6)
}

var fileDescriptor_4ef8bcd16d104cd6 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x8f, 0xd2, 0x40,
	0x18, 0x66, 0x96, 0x48, 0xc2, 0xe0, 0x85, 0x86, 0xc4, 0xd2, 0x98, 0x2e, 0xa2, 0x26, 0x84, 0x48,
	0x1b, 0xd8, 0xe8, 0x01, 0xbd, 0x50, 0xa3, 0xc6, 0x03, 0xd1, 0xb0, 0x7a, 0xf1, 0xb2, 0x99, 0xd2,
	0xb1, 0x34, 0xbb, 0x9d, 0x69, 0xfa, 0x4e, 0x71, 0xf7, 0x66, 0x3c, 0x7a, 0x32, 0xf1, 0x4f, 0x18,
	0x0f, 0x86, 0x83, 0x3f, 0x62, 0x8f, 0x1b, 0xbd, 0x78, 0xf1, 0x23, 0x70, 0xe0, 0x6f, 0x98, 0x76,
	0x66, 0x17, 0x15, 0x44, 0xcc, 0x5e, 0x98, 0xe1, 0xfd, 0x78, 0xde, 0x79, 0x9e, 0xe7, 0x2d, 0x6e,
	0x0d, 0x79, 0x18, 0x71, 0x20, 0xee, 0x01, 0xb5, 0x41, 0x90, 0xfd, 0x80, 0xf9, 0x61, 0xe0, 0x79,
	0x07, 0xf4, 0x05, 0x89, 0xa9, 0x3d, 0x6e, 0xbb, 0x54, 0x90, 0xb6, 0x2d, 0x0e, 0xad, 0x28, 0xe6,
	0x82, 0x6b, 0xd7, 0x16, 0xe5, 0xd6, 0x52, 0xb9, 0xa5, 0xca, 0x0d, 0x73, 0xc8, 0x21, 0xe4, 0x60,
	0xbb, 0x04, 0x16, 0x18, 0x43, 0x1e, 0x30, 0x89, 0x62, 0x5c, 0x52, 0xf9, 0x10, 0x7c, 0x7b, 0xdc,
	0x4e, 0x0f, 0x95, 0x28, 0x93, 0x30, 0x60, 0xdc, 0xce, 0x7e, 0x55, 0xa8, 0xe2, 0x73, 0x9f, 0x67,
	0x57, 0x3b, 0xbd, 0xa9, 0x68, 0x55, 0x22, 0xec, 0xc9, 0x84, 0xfc, 0xa3, 0x52, 0x77, 0x36, 0x62,
	0xb4, 0xfc, 0xf8, 0xac, 0xbb, 0x3e, 0x45, 0xb8, 0xd2, 0x07, 0xff, 0x69, 0xe4, 0x11, 0x41, 0xef,
	0x45, 0x7c, 0x38, 0x7a, 0x4c, 0x62, 0x12, 0x82, 0x76, 0x0b, 0x17, 0x49, 0x22, 0x46, 0x3c, 0x0e,
	0xc4, 0x91, 0x8e, 0x6a, 0xa8, 0x51, 0x74, 0xf4, 0x4f, 0x1f, 0x5b, 0x15, 0x35, 0xbb, 0xe7, 0x79,
	0x31, 0x05, 0xd8, 0x15, 0x71, 0xc0, 0xfc, 0xc1, 0xa2, 0x54, 0x7b, 0x84, 0x0b, 0x51, 0x86, 0xa0,
	0x6f, 0xd5, 0x50, 0xa3, 0xd4, 0xb9, 0x61, 0x6d, 0x22, 0xa1, 0x25, 0xa7, 0x3a, 0xc5, 0xe3, 0x6f,
	0xdb, 0xb9, 0x77, 0xf3, 0x49, 0x13, 0x0d, 0x14, 0x4c, 0xb7, 0xf7, 0x6a, 0x3e, 0x69, 0x2e, 0x06,
	0xbc, 0x9e, 0x4f, 0x9a, 0xbf, 0x40, 0xda, 0x87, 0x2b, 0x48, 0x9f, 0x11, 0x92, 0xa8, 0x75, 0x13,
	0x5f, 0xfe, 0x23, 0x94, 0x31, 0x1d, 0x50, 0x88, 0x38, 0x03, 0x5a, 0xff, 0x8a, 0xf0, 0x95, 0x3e,
	0xf8, 0x3d, 0xcf, 0x1b, 0xd0, 0x31, 0x65, 0x09, 0xbd, 0x9f, 0x30, 0x0f, 0x9e, 0xf0, 0x5d, 0x89,
	0xac, 0x14, 0xb9, 0x8d, 0x2f, 0x3e, 0x8f, 0x79, 0xb8, 0x47, 0x24, 0xf5, 0x7f, 0x8a, 0x52, 0x4a,
	0xab, 0x55, 0x48, 0x1b, 0xe1, 0x02, 0x09, 0x79, 0xc2, 0x84, 0x9e, 0xaf, 0xe5, 0x1b, 0xa5, 0x4e,
	0xd5, 0x52, 0x3d, 0xe9, 0xce, 0x9c, 0xa9, 0x70, 0x97, 0x07, 0xcc, 0xb9, 0x99, 0x6a, 0xf0, 0xfe,
	0xfb, 0x76, 0xc3, 0x0f, 0xc4, 0x28, 0x71, 0x53, 0xb2, 0xca, 0x71, 0x75, 0xb4, 0xc0, 0xdb, 0xb7,
	0xc5, 0x51, 0x44, 0x21, 0x6b, 0x00, 0xa5, 0x97, 0xc4, 0xef, 0x96, 0x53, 0xbd, 0x7e, 0x7b, 0x69,
	0xfd, 0x3a, 0xbe, 0xba, 0x86, 0xde, 0xa9, 0x0c, 0x9d, 0xcf, 0x5b, 0x38, 0xdf, 0x07, 0x5f, 0x7b,
	0x8b, 0x70, 0x79, 0x79, 0x21, 0xba, 0x9b, 0x19, 0xb9, 0x6a, 0x99, 0x0c, 0xe7, 0x3f, 0x7b, 0x57,
	0x98, 0xa4, 0x7d, 0x40, 0x58, 0xff, 0x1b, 0x05, 0xed, 0xc1, 0xc6, 0x03, 0xd6, 0x9b, 0x6c, 0x3c,
	0x3c, 0x37, 0xd0, 0xe9, 0x83, 0x8d, 0x0b, 0x2f, 0x53, 0x5f, 0x9c, 0x9d, 0xe3, 0xa9, 0x89, 0x4e,
	0xa6, 0x26, 0xfa, 0x31, 0x35, 0xd1, 0x9b, 0x99, 0x99, 0x3b, 0x99, 0x99, 0xb9, 0x2f, 0x33, 0x33,
	0xf7, 0xac, 0xba, 0x6a, 0x77, 0x33, 0x5f, 0xdd, 0x42, 0xf6, 0x75, 0xee, 0xfc, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0x00, 0xe0, 0x13, 0xf7, 0xaf, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateEpochParams(ctx context.Context, in *MsgUpdateEpochParams, opts ...grpc.CallOption) (*MsgUpdateParamsEpochResponse, error)
	AddRevenueFundsToStaking(ctx context.Context, in *MsgAddRevenueFundsToStakingParams, opts ...grpc.CallOption) (*MsgAddRevenueFundsToStakingResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateEpochParams(ctx context.Context, in *MsgUpdateEpochParams, opts ...grpc.CallOption) (*MsgUpdateParamsEpochResponse, error) {
	out := new(MsgUpdateParamsEpochResponse)
	err := c.cc.Invoke(ctx, "/composable.stakingmiddleware.v1beta1.Msg/UpdateEpochParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddRevenueFundsToStaking(ctx context.Context, in *MsgAddRevenueFundsToStakingParams, opts ...grpc.CallOption) (*MsgAddRevenueFundsToStakingResponse, error) {
	out := new(MsgAddRevenueFundsToStakingResponse)
	err := c.cc.Invoke(ctx, "/composable.stakingmiddleware.v1beta1.Msg/AddRevenueFundsToStaking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateEpochParams(context.Context, *MsgUpdateEpochParams) (*MsgUpdateParamsEpochResponse, error)
	AddRevenueFundsToStaking(context.Context, *MsgAddRevenueFundsToStakingParams) (*MsgAddRevenueFundsToStakingResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateEpochParams(ctx context.Context, req *MsgUpdateEpochParams) (*MsgUpdateParamsEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEpochParams not implemented")
}
func (*UnimplementedMsgServer) AddRevenueFundsToStaking(ctx context.Context, req *MsgAddRevenueFundsToStakingParams) (*MsgAddRevenueFundsToStakingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRevenueFundsToStaking not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateEpochParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateEpochParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateEpochParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.stakingmiddleware.v1beta1.Msg/UpdateEpochParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateEpochParams(ctx, req.(*MsgUpdateEpochParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddRevenueFundsToStaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddRevenueFundsToStakingParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddRevenueFundsToStaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.stakingmiddleware.v1beta1.Msg/AddRevenueFundsToStaking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddRevenueFundsToStaking(ctx, req.(*MsgAddRevenueFundsToStakingParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "composable.stakingmiddleware.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateEpochParams",
			Handler:    _Msg_UpdateEpochParams_Handler,
		},
		{
			MethodName: "AddRevenueFundsToStaking",
			Handler:    _Msg_AddRevenueFundsToStaking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "composable/stakingmiddleware/v1beta1/tx.proto",
}

func (m *MsgUpdateEpochParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEpochParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEpochParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsEpochResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsEpochResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsEpochResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddRevenueFundsToStakingParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddRevenueFundsToStakingParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddRevenueFundsToStakingParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddRevenueFundsToStakingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddRevenueFundsToStakingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddRevenueFundsToStakingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateEpochParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsEpochResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddRevenueFundsToStakingParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAddRevenueFundsToStakingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateEpochParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEpochParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEpochParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsEpochResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsEpochResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsEpochResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddRevenueFundsToStakingParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddRevenueFundsToStakingParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddRevenueFundsToStakingParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddRevenueFundsToStakingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddRevenueFundsToStakingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddRevenueFundsToStakingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
