name: Interchain Tests

on:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push
        id: build_push_image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/composablefi/centauri-ictest:latest
  test-start-cosmos-chain:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-start-cosmos
        env:
          BRANCH_CI: "latest"

  test-upgrade-cosmos-chain:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-upgrade
        env:
          BRANCH_CI: "latest"

  test-start-polkadot-chain:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-start-polkadot
        env:
          BRANCH_CI: "latest"

  test-validators:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-validator
        env:
          BRANCH_CI: "latest"

  # test-ibc-transfer:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-image
  #   steps:
  #     - name: Set up Go 1.20
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.20

  #     - name: checkout code
  #       uses: actions/checkout@v4

  #     - run: make ictest-ibc
  # env:
  # BRANCH_CI: "latest"

  # test-push-wasm:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-image
  #   steps:
  #     - name: Set up Go 1.20
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.20

  #     - name: checkout code
  #       uses: actions/checkout@v4

  #     - run: make ictest-push-wasm
  #       env:
  #         BRANCH_CI: "latest"
